# Generated by Django 3.2 on 2022-04-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=264)),
                ('address', models.TextField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('use_type', models.CharField(max_length=264)),
                ('roof_type', models.CharField(max_length=264)),
                ('is_local', models.BooleanField(default=True)),
                ('date_of_project', models.CharField(max_length=264)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='projects.projectsmodel')),
            ],
        ),
    ]
