# Generated by Django 3.2 on 2022-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=264)),
                ('length', models.CharField(max_length=264)),
                ('width', models.CharField(max_length=264)),
                ('address', models.TextField()),
                ('name', models.CharField(blank=True, max_length=264, null=True)),
                ('height', models.CharField(blank=True, max_length=264, null=True)),
                ('type_of_use', models.CharField(blank=True, max_length=264, null=True)),
                ('number_of_floor', models.CharField(blank=True, max_length=264, null=True)),
                ('has_half_floor', models.BooleanField(blank=True, null=True)),
                ('has_child_salon', models.BooleanField(blank=True, null=True)),
                ('has_crane', models.BooleanField(blank=True, null=True)),
                ('crane_weight', models.CharField(blank=True, max_length=264, null=True)),
                ('is_curved', models.BooleanField(blank=True, null=True)),
                ('is_double_side_inclined', models.BooleanField(blank=True, null=True)),
                ('is_single_side_inclined', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
