# Generated by Django 3.2 on 2022-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingmodel',
            name='is_salon',
            field=models.BooleanField(default=True),
        ),
    ]
