# Generated by Django 3.2 on 2022-04-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_orderingmodel_is_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
