# Generated by Django 3.2 on 2022-04-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='for_excebition',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='for_factory',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='for_project',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='for_sundry',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='for_workers',
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
