# Generated by Django 3.2 on 2022-04-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=264, null=True)),
                ('person_name', models.CharField(max_length=264)),
                ('comment', models.TextField()),
                ('picture', models.ImageField(default='comment/default/default.jpg', upload_to='comment')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='projects.projectsmodel')),
            ],
        ),
    ]
